### ISSUE TITLE
At the very end of lein compile, print a warning if the <enabled>true</enabled> is set in the config file

### ISSUE THREAD

**Issue by rarebreed** [RedHatQE/polarize#33]

**Comment by jsefler** [comment]
```Don't forget to set <enabled>false</enabled> under the <importer type="testcase"> section of your xml-config.xml file when you are done creating/updating testcases in Polarion.```

**Comment by rarebreed** [comment]
Fixed in c108141f433cd9afe6216bc19cc146e1010da5f8
