### ISSUE TITLE
Repository Status

### ISSUE THREAD

**Issue by JacobCallahan** [RedHatQE/polarize#64]
Hi @jstavel, we're checking in to see the status of this repository as part of an organization-level evaluation. Can you let us know the following?

1. Is this being actively developed/maintained?
2. Is this project in active use?
3. If not you, who is the primary contact for this project?

Thanks!

**Comment by jstavel** [comment]
Hi @JacobCallahan this repo provides a support libraries for a project polarizer-vertx. It is a service that is used by a team RHSMQE to send all test results into Polarion.

**Comment by JacobCallahan** [comment]
Thanks for the response!

**Comment by chirlo** [comment]
Hi, @jstavel  I was also curious about this project and wanted to ask: 

- Is this repository usable on its own , or does it require adding some extension to the polarion installation or such?
